use_frameworks!

platform :ios, '10.0'

target 'pods_test_Example' do
  pod 'pods_test', :path => '../'

  target 'pods_test_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
